services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: doctor_booking_system
      DB_USER: root
      DB_PASS: root

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doctor_booking_system
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/doctor_booking.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
