services:
  web:
    build: .
    container_name: mediqueue-web
    ports:
      - "80:80"
    environment:
      DB_HOST: database-medi.chqe2ei0yzi8.ap-south-1.rds.amazonaws.com
      DB_NAME: doctor_booking_system
      DB_USER: admin
      DB_PASS: medi0012
    restart: unless-stopped